https://www.mathworks.com/help/deeplearning/gs/create-simple-deep-learning-classification-network.html

~更換資料集與輸入規格~
a) 匯入 MerchData (在GetStartedWithTransferLearningExample資料夾)
將data抓進當前資料夾，或者 dataFolder = fullfile(toolboxdir('nnet'),'nndemos','nndatasets','MerchData');)
imds = imageDatastore("MerchData", ...
    IncludeSubfolders=true, ...
    LabelSource="foldernames");
numTrainFiles = 750;
[imdsTrain,imdsValidation,imdsTest] = splitEachLabel(imds,0.7,0.15,"randomized");

b) 修改網路架構
inputSize = [227 227 3];

c) 修改訓練參數
options = trainingOptions("adam", ...
    MaxEpochs=15, ...
    ValidationData=imdsValidation, ...
    ValidationFrequency=5, ...
    Plots="training-progress", ...
    Metrics="accuracy", ...
    Verbose=false);
accuracy = testnet(net,imdsTest,"accuracy")
